export const SUPABASE_URL = 'https://vfoxulljyqfkolixzwdq.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmb3h1bGxqeXFma29saXh6d2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5NjA2MDMsImV4cCI6MjA3ODUzNjYwM30._s7A5aDr2dGfCmEe-wdNfkF1SHq-_VIw4PvOBZYII00';
